name: Main

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install
      - name: Run lint check
        run: npm run lint

  check-version:
    # Ensures that the current version is later than the one on the marketplace
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install
      - name: Check version validity
        run: |
          export EXTENSION_ID=$(jq -r '.publisher' package.json).$(jq -r '.name' package.json)
          export PACKAGE_VERSION=$(jq -r '.version' package.json)
          export MARKETPLACE_VERSION=$(npx vsce show $EXTENSION_ID --json | jq -j '.versions[0].version')
          dpkg --compare-versions $PACKAGE_VERSION "gt" $MARKETPLACE_VERSION

  build-python-ly-bundle:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.x"
      - name: Cache requirements
        id: cache-requirements
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('**/requirements.txt') }}
      - name: Install dependencies
        if: steps.cache-requirements.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r ly/requirements.txt
      - name: Build python-ly
        run: |
          cd ly
          python build.py
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist-${{ matrix.os }}
          path: ly/dist

  prepublish-test:
    runs-on: ubuntu-latest
    needs:
      - build-python-ly-bundle
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm Install
      - name: Download artifact (linux)
        uses: actions/download-artifact@v2
        with:
          name: dist-ubuntu-latest
          path: ly/dist-linux
      - name: Download artifact (windows)
        uses: actions/download-artifact@v2
        with:
          name: dist-windows-latest
          path: ly/dist-windows
      - name: Download artifact (macos)
        uses: actions/download-artifact@v2
        with:
          name: dist-macos-latest
          path: ly/dist-macos
      - name: Run prepublish
        run: npm run vscode:prepublish

  release:
    # Only release when pushing to master
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs:
      - lint
      - check-version
      - build-python-ly-bundle
      - prepublish-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install
      - name: Download artifact (linux)
        uses: actions/download-artifact@v2
        with:
          name: dist-ubuntu-latest
          path: ly/dist-linux
      - name: Download artifact (windows)
        uses: actions/download-artifact@v2
        with:
          name: dist-windows-latest
          path: ly/dist-windows
      - name: Download artifact (macos)
        uses: actions/download-artifact@v2
        with:
          name: dist-macos-latest
          path: ly/dist-macos
      - name: Get tag version
        id: tag
        run: echo "::set-output name=tag::$(jq -r '.version' package.json)"
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.tag.outputs.tag }}
      - name: Publish extension
        run: npx vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
